models/Language.php
<?php

/**
 * This is the model class for table "language".
 *
 * The followings are the available columns in table 'language':
 * @property integer $id
 * @property string $name
 * @property string $ru
 * @property string $en
 * @property string $fi
 * @property string $de
 * @property string $fr
 * @property string $se
 * @property string $es
 * @property string $rut
 */
class Language extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'language';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>255),
			array('ru, en, fi, de, fr, se, es, rut', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, ru, en, fi, de, fr, se, es, rut', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'ru' => 'Ru',
			'en' => 'En',
			'fi' => 'Fi',
			'de' => 'De',
			'fr' => 'Fr',
			'se' => 'Se',
			'es' => 'Es',
			'rut' => 'Rut',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

//		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true, 'OR');
		$criteria->compare('ru',$this->ru,true, 'OR');
		$criteria->compare('en',$this->en,true, 'OR');
		$criteria->compare('fi',$this->fi,true, 'OR');
		$criteria->compare('de',$this->de,true, 'OR');
		$criteria->compare('fr',$this->fr,true, 'OR');
		$criteria->compare('se',$this->se,true, 'OR');
		$criteria->compare('es',$this->es,true, 'OR');
		$criteria->compare('rut',$this->rut,true, 'OR');

		return new CActiveDataProvider($this, 
		    array(
			'criteria'=>$criteria,
			'pagination'=>array('pageSize'=>30),
		    ),
		);
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Language the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

controllers/LanguageController.php
<?php
ini_set('error_reporting', E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);


class LanguageController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';
	
	const RU = 'ru'; // russian code
	const EN = 'en'; // the english one
	const FI = 'fi'; // finnish
	const DE = 'de'; // german
	const FR = 'fr'; // french
	const SE = 'se'; // swedish
	const ES = 'es'; // spannish
	const RUT = 'rut'; // russian translate
	const LANGS = [self::RU, self::EN, self::FI, self::DE, self::FR, self::SE, self::ES, self::RUT];

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
//			array('allow',  // allow all users to perform 'index' and 'view' actions
//				'actions'=>array('index','view'),
//				'users'=>array('*'),
//			),
//			array('allow', // allow authenticated user to perform 'create' and 'update' actions
//				'actions'=>array('create','update'),
//				'users'=>array('@'),
//			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete', 'index','view', 'create','update', 'simpleSearch', 'export'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Language;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Language']))
		{
			$model->attributes=$_POST['Language'];
			if($model->save()) {
				$this->actionExport();
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Language']))
		{
			$model->attributes=$_POST['Language'];
			if($model->save()) {
				$this->actionExport();
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();
		$this->actionExport();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Language',
		    array('pagination' => array(
		          'pageSize' => 30,
			 ),
		      )
		);
		
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin($lang = 'ru')
	{
		
		
		$model=new Language('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Language'])) {
			$model->attributes=$_GET['Language'];
		}
		$this->render('admin',array(
			'model'=>$model,
			'lang'=>$lang,

		));
	}
	
	public function actionExport($lang = 'ru')
	{

	    $outputDir = dirname(dirname(__FILE__)) . '/export/';
	    $outputCaption = '<?php // FILE: language constants, generated at ' . date("m.d.Y G:i:s") . PHP_EOL . 'return array ('. PHP_EOL;
	    $outputBottom = ');' . PHP_EOL;

	    
	    // получаем данные
	    $models = Language::model()->findAll();
	    foreach ($models as $key => $model) {
		foreach (self::LANGS as $lang) {
	            $line = '  ' . var_export($model->name, TRUE) ." => " . var_export($model->$lang, TRUE) . "," . PHP_EOL;
	            $outputArray[$lang][] = $line;
		}
		unset($models[$key]);
	    }

	    // пишем строчки в файлики по очереди
	    foreach ($outputArray as $key => $lines) {
	        $fileName[$key] = $outputDir . "uiconst.class.$key.php";
	        if (file_exists($fileName[$key])) {
	            unlink($fileName[$key]);
	        }
	        if (!$fileHandle[$key] = fopen($fileName[$key], 'a')) {
	            throw new Exception("Could not write to file $fileName[$key]");
	        }
	        fwrite($fileHandle[$key], $outputCaption);
	        unset($fileName[$key]);
    
		foreach ($lines as $id => $line) {
	             fwrite($fileHandle[$key], $line);
	             unset($lines[$id]);
	        }
	        fwrite($fileHandle[$key], $outputBottom);
	        fclose($fileHandle[$key]);
	    }

	    $this->render('export',array(
			'result'=>'done'
	    ));

	}
	
	
	public function actionSimpleSearch($lang = 'ru')
	{
		$model=new Language('search');
		$model->unsetAttributes();  // clear any default values
		
		if(isset($_GET['string'])) {

		    $_GET['Language']['ru'] = $_GET['string'];
		    $_GET['Language']['fi'] = $_GET['string'];
		    $_GET['Language']['en'] = $_GET['string'];
		    $_GET['Language']['de'] = $_GET['string'];
		    $_GET['Language']['fr'] = $_GET['string'];
		    $_GET['Language']['se'] = $_GET['string'];
		    $_GET['Language']['es'] = $_GET['string'];
		    $_GET['Language']['rut'] = $_GET['string'];
		}
		else {$_GET['string'] = null;}

		if(isset($_GET['Language'])) {
			$model->attributes=$_GET['Language'];
		}
		
		$this->render('admin',array(
			'model'=>$model,
			'lang' =>$lang,
			'string' =>$_GET['string']
		));
	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Language the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Language::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Language $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='language-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

views/language/_export.php
<?php
/* @var $this LanguageController */
/* @var $model Language */
/* @var $form CActiveForm */
?>

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl('language/export'),
	'method'=>'get',
	'id'=>'language-export-form',

)); ?>


<?php echo CHtml::submitButton('Export Languages'); ?>
<?php $this->endWidget(); ?>

views/language/_form.php
<?php
/* @var $this LanguageController */
/* @var $model Language */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'language-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>


	<div class="row">
		<?php echo $form->labelEx($model,'ru'); ?>
		<?php echo $form->textArea($model,'ru',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'ru'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'en'); ?>
		<?php echo $form->textArea($model,'en',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'en'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'fi'); ?>
		<?php echo $form->textArea($model,'fi',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'fi'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'de'); ?>
		<?php echo $form->textArea($model,'de',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'de'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'fr'); ?>
		<?php echo $form->textArea($model,'fr',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'fr'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'se'); ?>
		<?php echo $form->textArea($model,'se',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'se'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'es'); ?>
		<?php echo $form->textArea($model,'es',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'es'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'rut'); ?>
		<?php echo $form->textArea($model,'rut',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'rut'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

views/language/_formUpdate.php
<?php
/* @var $this LanguageController */
/* @var $model Language */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'language-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'ru'); ?>
		<?php echo $form->textArea($model,'ru',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'ru'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'en'); ?>
		<?php echo $form->textArea($model,'en',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'en'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'fi'); ?>
		<?php echo $form->textArea($model,'fi',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'fi'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'de'); ?>
		<?php echo $form->textArea($model,'de',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'de'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'fr'); ?>
		<?php echo $form->textArea($model,'fr',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'fr'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'se'); ?>
		<?php echo $form->textArea($model,'se',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'se'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'es'); ?>
		<?php echo $form->textArea($model,'es',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'es'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'rut'); ?>
		<?php echo $form->textArea($model,'rut',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'rut'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

views/language/_search.php
<?php
/* @var $this LanguageController */
/* @var $model Language */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>



	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>60,'maxlength'=>255)); ?>
	</div>


	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ru'); ?>
		<?php echo $form->textArea($model,'ru',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'en'); ?>
		<?php echo $form->textArea($model,'en',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'fi'); ?>
		<?php echo $form->textArea($model,'fi',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'de'); ?>
		<?php echo $form->textArea($model,'de',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'fr'); ?>
		<?php echo $form->textArea($model,'fr',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'se'); ?>
		<?php echo $form->textArea($model,'se',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'es'); ?>
		<?php echo $form->textArea($model,'es',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'rut'); ?>
		<?php echo $form->textArea($model,'rut',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

views/language/_search_simple.php
<?php
/* @var $this LanguageController */
/* @var $model Language */
/* @var $form CActiveForm */
?>

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl('language/simpleSearch'),
	'method'=>'get',
	'id'=>'language-form',

)); ?>

<tr class="odd"><td></td>
<div class="compactRadioGroup">
            <?php
                            echo CHtml::radioButtonList('lang', $lang,
                                            array(  'ru' => 'ru',
                                                    'en' => 'en',
                                            	    'fi' => 'fi',
                                            	    'de' => 'de',
                                            	    'fr' => 'fr',
                                            	    'se' => 'se',
                                            	    'es' => 'es',
                                            	    'rut' => 'rut'
                                            	     ),
                                            array( 'separator' => "",
                                        	    'template' => '<td>{input}</td>'
                                             )         
                                             );
            ?>
</div>
<td></td>
</tr>
<tr class="odd">
<td id="language-grid_c8" colspan="1"><?php echo $form->textField($model,'name',array('size'=>45,'maxlength'=>255)); ?></td>
<td id="language-grid_c9" colspan="8"><?php echo CHtml::textField('string', $string ,array('size'=>45));?></td>

<td><?php echo CHtml::submitButton('Submit'); ?>
<?php $this->endWidget(); ?>

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl('language/admin'),
	'method'=>'get',
)); ?>
<?php echo CHtml::submitButton('x'); ?>
</td></tr>
<?php $this->endWidget(); ?>

views/language/_view.php
<?php
/* @var $this LanguageController */
/* @var $data Language */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('ru')); ?>:</b>
	<?php echo CHtml::encode($data->ru); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('en')); ?>:</b>
	<?php echo CHtml::encode($data->en); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fi')); ?>:</b>
	<?php echo CHtml::encode($data->fi); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('de')); ?>:</b>
	<?php echo CHtml::encode($data->de); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fr')); ?>:</b>
	<?php echo CHtml::encode($data->fr); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('se')); ?>:</b>
	<?php echo CHtml::encode($data->se); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('es')); ?>:</b>
	<?php echo CHtml::encode($data->es); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('rut')); ?>:</b>
	<?php echo CHtml::encode($data->rut); ?>
	<br />
	<?php /*

	*/ ?>

</div>

views/language/admin.php
<?php
/* @var $this LanguageController */
/* @var $model Language */

$this->breadcrumbs=array(
	'Languages'=>array('index'),
	'Manage',
);

$this->menu=array(
//	array('label'=>'List Language', 'url'=>array('index')),
	array('label'=>'Create Language', 'url'=>array('create')),
	array('label'=>'Export Languages', 'url'=>array('export')),

);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#language-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Languages</h1>

<?php
echo CHtml::image(Yii::app()->request->baseUrl.'/images/logo.png','this is an alternative text',array('width'=>186,'height'=>126));
?>

<div id="language-grid" class="grid-view">
<div class="summary">Select Language</div>
<table class="items">
<thead>
<tr>
<th id="language-grid_c10">NAME</th>

<th id="language-grid_c0">RU</th>
<th id="language-grid_c1">EN</th>
<th id="language-grid_c2">FI</th>
<th id="language-grid_c3">FE</th>
<th id="language-grid_c4">FR</th>
<th id="language-grid_c5">SE</th>
<th id="language-grid_c6">ES</th>
<th id="language-grid_c7">RUT</th>
<th id="language-grid_c7">DO</th>

</tr>
</thead>
<tbody>
<tr class="odd">

<div class="search-form">
<?php 
	isset($_GET['string']) ? $string = $_GET['string'] : $string = null;
	$this->renderPartial('_search_simple',array(
	'model'=>$model,
	'lang'=>$lang,
	'string'=>$string,
)); ?>
</div>


</tbody>
</table>
<div class="keys" style="display:none" title="/index.php?r=language/admin&amp;lang=<?php echo $lang ?>"><span>1</span></div>
</div>

<div class="search-form">
<?php 
	$this->renderPartial('_export',array(
)); ?>
</div>


<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'language-grid',
	'dataProvider'=>$model->search(),
	'ajaxUpdate'=>false,
//	'filter'=>$model,
	'columns'=>array(
//		'id',
		'name',
		$lang,
/*
		'ru',
		'en',
		'fi',
		'de',
		'fr',
		'se',
		'es',
		'rut',

		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

views/language/create.php
<?php
/* @var $this LanguageController */
/* @var $model Language */

$this->breadcrumbs=array(
	'Languages'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'Manage Language', 'url'=>array('admin')),
);
?>

<h1>Create Language</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

views/language/export.php
<?php
/* @var $this LanguageController */
/* @var $model Language */

$this->breadcrumbs=array(
	'Languages'=>array('index'),
);

$this->menu=array(
	array('label'=>'Create Language', 'url'=>array('create')),
	array('label'=>'Manage Language', 'url'=>array('admin')),
);
?>

<h1>Export Language: <?php echo $result; ?></h1>

views/language/index.php
<?php
/* @var $this LanguageController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Languages',
);

$this->menu=array(
	array('label'=>'Create Language', 'url'=>array('create')),
	array('label'=>'Manage Language', 'url'=>array('admin')),
);
?>

<h1>Languages</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

views/language/update.php
<?php
/* @var $this LanguageController */
/* @var $model Language */

$this->breadcrumbs=array(
	'Languages'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'Create Language', 'url'=>array('create')),
	array('label'=>'View Language', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Language', 'url'=>array('admin')),
);
?>

<h1>Update <?php echo $model->name; ?></h1>

<?php $this->renderPartial('_formUpdate', array('model'=>$model)); ?>

views/language/view.php
<?php
/* @var $this LanguageController */
/* @var $model Language */

$this->breadcrumbs=array(
	'Languages'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'Create Language', 'url'=>array('create')),
	array('label'=>'Update Language', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Language', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Language', 'url'=>array('admin')),
);
?>

<h1>View Language #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		'ru',
		'en',
		'fi',
		'de',
		'fr',
		'se',
		'es',
		'rut',
	),
)); ?>